algoritmo "Lista de Exercícios4"
var
morangoate5,morangoacimade5: real
quantidadeKg: inteiro

inicio
escreva("QUANTOS KG DE MORANGO VOCE DESEJA? ")
leia(quantidadeKg)

se (quantidadeKg<=5)entao
escreva("o valor a ser pago é: ", quantidadeKg*2.50)
senao
escreva("o valor a ser pago é: ", quantidadeKg*2.20)
fimse

se (quantidadeKg<=5)entao
escreva("o valor a ser pago é: ", quantidadeKg*2.50)
senao
escreva("o valor a ser pago é: ", quantidadeKg*2.20)
fimse



fimalgoritmo