algoritmo "matrizes 3"

var
nome: vetor[1..3] de caracter
n,i:inteiro
notas: vetor[1..3, 1..3] de real
inicio



para n de 1 ate 3 faca
escreva("DIGITE A",n,"º DISCIPLINA: ")
leia(nome[n])

para i de 1 ate 3 faca

ESCREVA("digite as notas: ")
leia(notas[i])

fimpara
fimpara

limpatela

para n de 1 ate 3 faca
escreval("AS NOTA DA MATERIA de ",nome[n])

para i de 1 ate 3 faca
escreval (notas[i])

fimpara
fimpara



fimalgoritmo